version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
     - image: circleci/python:3.7

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "backend/Pipfile.lock" }}
      - run:
          name: project setup
          working_directory: backend
          command: |
            sudo pip install pipenv
            pipenv install --system
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "backend/Pipfile.lock" }}
          paths:
            - ./backend/venv
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: run code style
          working_directory: backend
          command: |
            pycodestyle src/
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build