version: 2
jobs:
  backend:
    working_directory: ~/app
    docker:
     - image: circleci/python:3.7

    steps:
      - checkout
      - run: 
          name: Chwon
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages            
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "backend/Pipfile.lock" }}
      - run:
          name: Project Setup
          working_directory: backend
          command: |
            sudo pip install pipenv
            pipenv install --dev --system
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "backend/Pipfile.lock" }}
          paths:
            - ./backend/venv
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Run Code Style
          working_directory: backend
          command: pipenv run lint || exit 1
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  frontend:
    working_directory: ~/app
    docker:
      - image: circleci/node:12.8

    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Project Setup
          working_directory: frontend
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "frontend/package-lock.json" }}
          paths:
            - ./frontend/node_modules
      - run:
          name: Run Code Style
          working_directory: frontend
          command: npm run lint
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

workflows:
  version: 2
  build_and_test:
    jobs:
      - backend
      - frontend